version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ClaimAssure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:9006
    volumes:
      - .:/app
    ports:
      - "9006:9006"
    depends_on:
      - db

volumes:
  db_data:
