from django.db import models
from PreAuth.models import *

from rest_framework.response import Response
# Create your models here.


class CaseSheet(models.Model):
    user = models.ForeignKey(User , related_name= "CaseSheet_user" , on_delete=models.CASCADE)
    caseNumber = models.OneToOneField(PreAuthLinkcaseNumber , related_name='CaseSheet_caseNumber' ,  to_field= 'caseNumber', on_delete=models.CASCADE)
    admitCaseClinicalSheet =  models.FileField(upload_to= 'ClaimDocuments/CaseSheet' , blank = True ,     null = True ) 
    icp =  models.FileField(upload_to= 'ClaimDocuments/CaseSheet' , blank = True ,     null = True ) 
    medicationChart =  models.FileField(upload_to= 'ClaimDocuments/CaseSheet' , blank = True ,     null = True ) 
    initialSheet =  models.FileField(upload_to= 'ClaimDocuments/CaseSheet' , blank = True ,     null = True ) 
    tprChart =  models.FileField(upload_to= 'ClaimDocuments/CaseSheet' , blank = True ,     null = True ) 
    vitalChart =  models.FileField(upload_to= 'ClaimDocuments/CaseSheet' , blank = True ,     null = True ) 
    losStayChart =  models.FileField(upload_to= 'ClaimDocuments/CaseSheet' , blank = True ,     null = True ) 
    caseSheetOtherDocuments =  models.FileField(upload_to= 'ClaimDocuments/CaseSheet' , blank = True ,     null = True ) 
    date_modified = models.DateTimeField(auto_now=True)

class LabTest(models.Model):
    user = models.ForeignKey(User , related_name= "LabTest_user" , on_delete=models.CASCADE)
    caseNumber = models.OneToOneField(PreAuthLinkcaseNumber , related_name='LabTest_caseNumber', to_field= 'caseNumber' , on_delete=models.CASCADE)
    microbiology = models.FileField(upload_to= 'ClaimDocuments/Lab Test' , blank = True ,     null = True ) 
    biochemistry =  models.FileField(upload_to= 'ClaimDocuments/Lab Test' , blank = True ,     null = True ) 
    pathology = models.FileField(upload_to= 'ClaimDocuments/Lab Test' , blank = True ,     null = True )
    serologyInvestigation = models.FileField(upload_to= 'ClaimDocuments/Lab Test' , blank = True ,     null = True )
    labTestOtherDocuments = models.FileField(upload_to= 'ClaimDocuments/Lab Test', blank = True , null = True )
    date_modified = models.DateTimeField(auto_now=True)

class Reports(models.Model):
    user = models.ForeignKey(User , related_name= "Reports_user" , on_delete=models.CASCADE)
    caseNumber = models.OneToOneField(PreAuthLinkcaseNumber , related_name='Reports_caseNumber', to_field= 'caseNumber' ,  on_delete=models.CASCADE)
    radiology = models.FileField(upload_to= 'ClaimDocuments/Reports' , blank = True ,     null = True )
    otprocedureSheets = models.FileField(upload_to= 'ClaimDocuments/Reports' , blank = True ,     null = True )
    anaesthesiaNotes = models.FileField(upload_to= 'ClaimDocuments/Reports' , blank = True ,     null = True )
    reportsOtherDocuments = models.FileField(upload_to= 'ClaimDocuments/Reports' , blank = True , null = True )
    date_modified = models.DateTimeField(auto_now=True)
class DischargeSummary(models.Model):
    user = models.ForeignKey(User , related_name= "DischargeSummary_user" , on_delete=models.CASCADE)
    caseNumber = models.OneToOneField(PreAuthLinkcaseNumber , related_name='DischargeSummary_caseNumber', to_field= 'caseNumber',  on_delete=models.CASCADE)
    dischargeDate = models.DateTimeField()
    dischargeType = models.CharField(max_length=255 ) # drop down 
    dischargeSummaryDocument = models.FileField(upload_to= 'ClaimDocuments/Discharge Summary' , blank = True ,     null = True ) 
    dischargeSummaryOtherDocuments = models.FileField(upload_to= 'ClaimDocuments/Discharge Summary' , blank = True , null = True )
    date_modified = models.DateTimeField(auto_now=True)

class DeathSummary(models.Model):
    user = models.ForeignKey(User , related_name= "DeathSummary_user" , on_delete=models.CASCADE)
    caseNumber = models.OneToOneField(PreAuthLinkcaseNumber , related_name='DeathSummary_caseNumber',  to_field= 'caseNumber' ,  on_delete=models.CASCADE)
    mortalityAudit  = models.FileField(upload_to= 'ClaimDocuments/Death Summary' , blank = True ,     null = True ) 
    deathCertificate = models.FileField(upload_to= 'ClaimDocuments/Death Summary' , blank = True ,     null = True ) 
    deathSummaryOtherDocuments = models.FileField(upload_to= 'ClaimDocuments/Death Summary' , blank = True , null = True )
    date_modified = models.DateTimeField(auto_now =True ) 


class BloodDocuments(models.Model):
    user = models.ForeignKey(User , related_name= "BloodDocuments_user" , on_delete=models.CASCADE)
    caseNumber = models.OneToOneField(PreAuthLinkcaseNumber , related_name='BloodDocuments_caseNumber',  to_field= 'caseNumber' ,  on_delete=models.CASCADE)
    bloodTransfusion = models.FileField(upload_to= 'ClaimDocuments/Blood Documents' , blank = True ,     null = True ) 
    btSticker = models.FileField(upload_to= 'ClaimDocuments/Blood Documents' , blank = True ,     null = True ) 
    crossMatchReport = models.FileField(upload_to= 'ClaimDocuments/Blood Documents' , blank = True ,     null = True ) 
    bloodOtherDocuments = models.FileField(upload_to= 'ClaimDocuments/OtherDoc' , blank = True , null = True )
    date_modified = models.DateTimeField(auto_now=True)
    # Status = models.CharField(max_length=255 )

class ClaimManagemntStatus(models.Model):
    user = models.ForeignKey(User , related_name= "ClaimManagemntStatus_user" , on_delete=models.CASCADE , blank = True , null = True )
    caseNumber = models.OneToOneField(PreAuthLinkcaseNumber , related_name='ClaimManagemntStatus_caseNumber',  to_field= 'caseNumber' ,  on_delete=models.CASCADE)
    status = models.CharField(max_length=50 , blank = True , null = True)
    
class DumpExcel(models.Model):
    user = models.ForeignKey(User , related_name="dumps_user" , on_delete= models.CASCADE)
    caseNo = models.OneToOneField( PreAuthLinkcaseNumber , related_name='DumpExcel_caseNumber',  to_field= 'caseNumber' ,  on_delete=models.CASCADE , primary_key=True )
    claimNo = models.CharField(max_length=255 , blank = True , null = True)
    registrationNumber = models.CharField(max_length=255 , blank = True , null = True)
    nhmpID = models.CharField(max_length=255 , blank = True , null = True)
    familyId = models.CharField(max_length=255 , blank = True , null = True)
    patientDistrict = models.CharField(max_length=255 , blank = True , null = True)
    gender = models.CharField(max_length=255 , blank = True , null = True)
    age = models.IntegerField()
    categoryDetails = models.CharField(max_length=255 , blank = True , null = True)
    procedureDetails = models.TextField(max_length=255 , blank = True , null = True)
    caseType = models.CharField(max_length=255 , blank = True , null = True)
    caseStatus = models.CharField(max_length=255 , blank = True , null = True)
    hospitalName = models.CharField(max_length=255 , blank = True , null = True)
    hospitalCode = models.CharField(max_length=255 , blank = True , null = True)
    hospitalDistrict = models.CharField(max_length=255 , blank = True , null = True)
    preauthAmount =models.CharField(max_length=255, blank= True , null = True)
    claimInitaiatedAmount = models.CharField(max_length=255, blank= True , null = True)
    cpdApprovedAmount = models.CharField(max_length=255, blank= True , null = True)
    claimApprovedAmount = models.CharField(max_length=255 , blank = True , null = True)
    assignedFlag = models.CharField(max_length=255 , blank = True , null = True)
    assignedUser = models.CharField(max_length=255 , blank = True , null = True)
    assignedGroup = models.CharField(max_length=255 , blank = True , null = True)
    ipNumber = models.CharField(max_length=255, blank= True , null = True)
    preauthApprovedAmount = models.CharField(max_length=255, blank= True , null = True)

    ipRegistrationDate = models.DateField(  blank= True , null = True)
    admissionDate = models.DateTimeField( blank= True , null = True)
    preauthDate = models.DateTimeField( blank= True , null = True)
    preauthApproveDate =  models.DateTimeField(blank= True , null = True)
    preauthRejectedDate = models.DateTimeField(blank= True , null = True)
    surgeryDate =models.DateTimeField(blank= True , null = True)
    deathDate =models.DateTimeField( blank= True , null = True)
    dischargeDate = models.DateTimeField( blank= True , null = True)
    claimSubmittedDate = models.DateTimeField(blank= True , null = True)
    actualclaimSubmittedDate =models.DateTimeField( blank= True , null = True)
    actualRegistrationDate = models.DateTimeField(blank= True , null = True)
    date_modified = models.DateTimeField(auto_now_add= True)

    
    

class MPClaimPaidExcel(models.Model):
    user = models.ForeignKey(User, related_name = 'MPClaimPaidExcel_user' , on_delete= models.CASCADE)
    caseNumber = models.ForeignKey( PreAuthLinkcaseNumber , related_name='MPClaimPaidExcel_caseNumber',  to_field= 'caseNumber' ,  on_delete=models.CASCADE )
    workflowStatus	= models.CharField(max_length=255 , blank = True , null = True)
    statusUpdateDate	 = models.DateTimeField(blank = True , null = True)
    nhmpID	= models.CharField(max_length=255 , blank = True , null = True)
    familyId	= models.CharField(max_length=255 , blank = True , null = True)
    patientName	= models.CharField(max_length=255 , blank = True , null = True)
    age	= models.IntegerField( )
    gender	 = models.CharField(max_length=255 , blank = True , null = True)
    patientsHomeDistrict	= models.CharField(max_length=255 , blank = True , null = True)
    patientsHomeState = models.CharField(max_length=255 , blank = True ,  null  = True)	
    patientPhoneNo	= models.PositiveBigIntegerField( blank = True , null = True)
    address	= models.TextField(max_length=255 , blank = True , null = True)
    communicationAddress	 = models.TextField(max_length=255 , blank = True)
    communicationContactNo =  models.CharField( max_length=255 ,blank = True , null = True)
    communicationVillage = 	models.CharField(max_length=255 , blank = True ,  null  = True)
    communicationMandal = models.CharField(max_length=255 , blank = True ,  null  = True) 	
    communicationDistrict = models.CharField(max_length=255 , blank = True ,  null  = True)
    communicationState	= models.CharField(max_length=255 , blank = True ,  null  = True)
    speciality	= models.CharField(max_length=255 , blank = True ,  null  = True)
    patientIPOP	= models.CharField(max_length=255 , blank = True ,  null  = True)
    procedureCode	 = models.CharField(max_length=255 , blank = True ,  null  = True)
    procedure	= models.TextField(max_length=255 , blank = True ,  null  = True)
    procedureAutoApprove = models.CharField(max_length=255 , blank = True ,  null  = True)
    medicalOrSurgery	= models.CharField(max_length=255 , blank = True ,  null  = True)
    ipRegistrationDate = models.DateTimeField( blank = True ,  null  = True)	
    hospitalName	= models.CharField(max_length=255 , blank = True ,  null  = True)
    admissionDate	= models.DateTimeField(max_length=255 ,blank = True ,  null  = True)
    preAuthInitiationDate = models.DateTimeField(max_length=255 , blank = True ,  null  = True)	
    preAuthInitiationAmount	= models.CharField(max_length=255 , blank = True ,  null  = True)
    preAuthCancelDate	= models.DateTimeField( blank = True ,  null  = True)
    preAuthApprovalDate	= models.DateTimeField( blank = True ,  null  = True)
    preAuthApprovalAmount	= models.CharField(max_length=255 , blank = True ,  null  = True)
    preAuthRejectionDate	= models.DateTimeField( blank = True ,  null  = True)
    enhancementFlag	=  models.CharField(max_length=255 , blank = True ,  null  = True)
    enhancementApprovedAmount	= models.CharField(max_length=255 , blank = True ,  null  = True)
    surgeryDate	= models.DateTimeField( blank = True ,  null  = True)
    dischargeDate	= models.DateTimeField( blank = True ,  null  = True)
    deathDate	= models.DateTimeField( blank = True ,  null  = True)
    claimRaisedDate = models.DateTimeField( blank = True ,  null  = True)	
    claimPaidAmount= models.CharField(max_length=255 , blank = True ,  null  = True)
    cpdApprovedDate	= models.DateTimeField( blank = True ,  null  = True)
    cpdRejectedDate	= models.DateTimeField( blank = True ,  null  = True)
    shaApprovedDate = models.DateTimeField( blank = True ,  null  = True)
    claimPaidDate	= models.DateTimeField( blank = True ,  null  = True)
    claimUTRNumber	= models.CharField(max_length=255 , blank = True ,  null  = True)
    hospitalDistrict	= models.CharField(max_length=255 , blank = True ,  null  = True)
    hospitalState	= models.CharField(max_length=255 , blank = True ,  null  = True)
    preAuthApprovalRemarks	= models.TextField(max_length=255 , blank = True ,  null  = True)
    preAuthRejectionRemarks	= models.TextField(max_length=255 , blank = True ,  null  = True)
    claimApprovalRemarks	= models.TextField(max_length=255 , blank = True ,  null  = True)
    claimRejectionRemarks	= models.TextField(max_length=255 , blank = True ,  null  = True)
    claimInitiatedAmount	= models.CharField(max_length=255 , blank = True ,  null  = True)
    rfAmount	=models.CharField(max_length=255 , blank = True ,  null  = True)
    tdsAmount	= models.CharField(max_length=255 , blank = True ,  null  = True)
    amountPaidToHospital	= models.CharField(max_length=255 , blank = True ,  null  = True)
    claimApprovedAmount	= models.CharField(max_length=255 , blank = True ,  null  = True)
    claimUpdatedDate	= models.DateTimeField( blank = True ,  null  = True)
    preauthPendingRemarks	= models.TextField(max_length=255 , blank = True ,  null  = True)
    preauthPendingDate	= models.DateTimeField( blank = True ,  null  = True)
    preauthPendingUpdatedRemarks= models.TextField(max_length=255 , blank = True ,  null  = True)
    preauthPendingUpdatedDate	= models.DateTimeField(max_length=255 , blank = True ,  null  = True)
    claimPendingRemarks	= models.TextField(max_length=255 , blank = True ,  null  = True)
    claimPendingDate	= models.DateTimeField(blank = True ,  null  = True)
    claimPendingUpdatedRemarks	= models.TextField(max_length=255 , blank = True ,  null  = True)
    claimPendingUpdatedDate	= models.DateTimeField(max_length=255 , blank = True ,  null  = True)
    lastUpdatedUser	= models.CharField(max_length=255 , blank = True ,  null  = True)
    isAadharBenificaiary = models.CharField(max_length=255 , blank = True ,  null  = True)	
    bioAuthAtRegistration  = models.CharField(max_length=255 , blank = True ,  null  = True)	
    bioAuthAtdischarge = models.CharField(max_length=255 , blank = True ,  null  = True)
    erroneousInitiatedAmount = models.CharField(max_length=255 , blank = True ,  null  = True)	
    erroneousInitiatedDate = models.DateTimeField(max_length=255 , blank = True ,  null  = True)
    erroneousApprovedAmount = models.CharField(max_length=255 , blank = True ,  null  = True)	
    erroneousApprovedDate	= models.DateTimeField(max_length=255 , blank = True ,  null  = True)
    erroneousPaidDate	= models.DateTimeField(max_length=255 , blank = True ,  null  = True)
    erroneousUTRNumber	= models.CharField(max_length=255 , blank = True ,  null  = True)
    ipNumber	= models.CharField(max_length=255 , blank = True ,  null  = True)
    cpdPendingCount	= models.CharField(max_length=255 , blank = True ,  null  = True)
    cpdProcessingTime	= models.CharField(max_length=255 , blank = True ,  null  = True)
    revokedCase	= models.CharField(max_length=255 , blank = True ,  null  = True)
    revokedDate	= models.DateTimeField(max_length=255 , blank = True ,  null  = True)
    revokedRemarks	= models.TextField(max_length=255 , blank = True ,  null  = True)
    insuranceLiableAmount	= models.CharField(max_length=255 , blank = True ,  null  = True)
    trustLiableAmount	= models.CharField(max_length=255 , blank = True ,  null  = True)
    patientLiableAmount	= models.CharField(max_length=255 , blank = True ,  null  = True)
    actualRegistrationDate = models.DateTimeField(max_length=255 , blank = True ,  null  = True)
    preAuthQueryStatus	= models.CharField(max_length=255 , default= 'Pending')
    ClaimQueryStatus	= models.CharField(max_length=255 , default= 'Pending')
    date_modified = models.DateTimeField(auto_now_add= True)
    



