# Generated by Django 4.1.5 on 2023-04-03 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClaimManagement', '0016_alter_mpclaimpaidexcel_actualregistrationdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAuthQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=255)),
                ('documents', models.FileField(blank=True, null=True, upload_to='Query/PreAuth')),
                ('caseNumberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PreAuthQuery_caseNumber', to='ClaimManagement.mpclaimpaidexcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_PreAuthQuery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=255)),
                ('documents', models.FileField(blank=True, null=True, upload_to='Query/Claim')),
                ('caseNumberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClaimQuery_caseNumber', to='ClaimManagement.mpclaimpaidexcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_ClaimQuery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
