# Generated by Django 4.1.5 on 2023-04-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0002_claimquery_date_modified_preauthquery_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimquery',
            name='status',
            field=models.CharField(blank=True, default='Intended', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preauthquery',
            name='status',
            field=models.CharField(blank=True, default='Attended', max_length=50, null=True),
        ),
    ]
