# Generated by Django 4.1.5 on 2023-04-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0004_alter_claimquery_status_alter_preauthquery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimquery',
            name='status',
        ),
        migrations.RemoveField(
            model_name='preauthquery',
            name='status',
        ),
    ]
