# Generated by Django 4.1.5 on 2023-03-28 11:39

import PreAuth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('nhmpID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('nameOfPatient', models.CharField(max_length=255)),
                ('adharPhotograph', models.ImageField(blank=True, null=True, upload_to='AdharCard_PhotoGraphs')),
                ('adharNumber', models.PositiveBigIntegerField(unique=True, validators=[PreAuth.models.validate_length])),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('mobileNumber', models.PositiveBigIntegerField(blank=True, null=True, validators=[PreAuth.models.validate_number])),
                ('alternativeNumber', models.PositiveBigIntegerField(blank=True, null=True, validators=[PreAuth.models.validate_number])),
                ('addressLine1', models.CharField(blank=True, max_length=255, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('rationCardNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('rationCardPhotograph', models.ImageField(blank=True, null=True, upload_to='RationCard_Photographs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreAuthDocument',
            fields=[
                ('preAuthID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('dateOfAdmission', models.DateTimeField(null=True)),
                ('dateOfPreAuth', models.DateTimeField(null=True)),
                ('hospitalName', models.CharField(max_length=255, null=True)),
                ('hospitalCode', models.CharField(max_length=255, null=True)),
                ('justification', models.FileField(blank=True, null=True, upload_to='PreAuthDocuments/justification')),
                ('on_BedPhotograph', models.FileField(blank=True, null=True, upload_to='PreAuthDocuments/on_bedPhotograph')),
                ('admitCaseSheet', models.FileField(blank=True, null=True, upload_to='PreAuthDocuments/admitCaseSheet')),
                ('labReport', models.FileField(blank=True, null=True, upload_to='PreAuthDocuments/labReport')),
                ('radiologyReport', models.FileField(blank=True, null=True, upload_to='PreAuthDocuments/radiologyReport')),
                ('claimAssure_status', models.CharField(blank=True, default='PreAuth Created', max_length=100, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('personalInfoID', models.ForeignKey(db_column='personalInfo', on_delete=django.db.models.deletion.CASCADE, related_name='PreAuth_personal', to='PreAuth.personalinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Preauth_document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreAuthLinkcaseNumber',
            fields=[
                ('caseNumber', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('preAuthID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PreAuth_preAuthID', to='PreAuth.preauthdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PreAuthLinkcaseNumber_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreAuthQuery',
            fields=[
                ('caseNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='PreAuthQuery_caseNumber', serialize=False, to='PreAuth.preauthlinkcasenumber')),
                ('query', models.TextField(blank=True, max_length=255, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='Query/PreAuth_Query')),
            ],
        ),
        migrations.CreateModel(
            name='PreAuthEnhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='PreAuthDocuments/Enhancement_Documents')),
                ('preAuthID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PreAuthEnhancement_PreAuthDocument', to='PreAuth.preauthdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PreAuthEnhancement_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
