# Generated by Django 4.1.5 on 2023-03-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreAuthQuery',
        ),
    ]
