# Generated by Django 4.1.5 on 2023-05-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0002_delete_preauthquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
