# Generated by Django 4.1.5 on 2023-05-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0002_delete_preauthquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preauthlinkcasenumber',
            name='preAuthID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PreAuth_preAuthID', to='PreAuth.preauthdocument'),
        ),
    ]
