# Generated by Django 4.1.5 on 2023-05-15 13:21

import PreAuth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0003_alter_preauthlinkcasenumber_preauthid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='adharNumber',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, validators=[PreAuth.models.validate_length]),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
