# Generated by Django 4.1.5 on 2023-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0004_alter_personalinfo_adharnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='nameOfPatient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
