# Generated by Django 4.1.5 on 2023-05-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0003_alter_personalinfo_gender'),
        ('PreAuth', '0005_alter_personalinfo_nameofpatient'),
    ]

    operations = [
    ]
