# Generated by Django 4.1.5 on 2023-03-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0002_alter_mpclaimpaidexcel_actualregistrationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='claimPaidAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
