# Generated by Django 4.1.5 on 2023-03-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0005_alter_mpclaimpaidexcel_cpdapproveddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='cpdRejectedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
