# Generated by Django 4.1.5 on 2023-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0007_alter_mpclaimpaidexcel_shaapproveddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='claimPaidDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
