# Generated by Django 4.1.5 on 2023-03-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0008_alter_mpclaimpaidexcel_claimpaiddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='claimUpdatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
