# Generated by Django 4.1.5 on 2023-03-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0009_alter_mpclaimpaidexcel_claimupdateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='preauthPendingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
