# Generated by Django 4.1.5 on 2023-03-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0010_alter_mpclaimpaidexcel_preauthpendingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='preauthPendingUpdatedDate',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
