# Generated by Django 4.1.5 on 2023-03-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0011_alter_mpclaimpaidexcel_preauthpendingupdateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='claimPendingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
