# Generated by Django 4.1.5 on 2023-03-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0012_alter_mpclaimpaidexcel_claimpendingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='claimPendingUpdatedDate',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
