# Generated by Django 4.1.5 on 2023-03-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0014_alter_mpclaimpaidexcel_erroneousinitiateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='erroneousApprovedDate',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='erroneousPaidDate',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
