# Generated by Django 4.1.5 on 2023-03-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0015_alter_mpclaimpaidexcel_erroneousapproveddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='actualRegistrationDate',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='revokedDate',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
