# Generated by Django 4.1.5 on 2023-04-11 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClaimManagement', '0016_alter_mpclaimpaidexcel_actualregistrationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpclaimpaidexcel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='MPClaimPaidExcel_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
