# Generated by Django 4.1.5 on 2023-05-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0020_rename_query_status_mpclaimpaidexcel_claimquerystatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathsummary',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
