# Generated by Django 4.1.5 on 2023-05-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0021_alter_deathsummary_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathsummary',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
