# Generated by Django 4.1.5 on 2023-05-25 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0022_alter_deathsummary_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpexcel',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpclaimpaidexcel',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
